# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  #contentDir: content/en

# German
de:
  languageCode: de
  contentDir: content/de
  title: Die neue klimapolitische Spaltung
  params:
    description: 'Informationen zum Forschungsprojekt Die neue klimapolitische Spaltung.'
  menu:
    main:
      - name: Ãœber das Projekt
        url: about
        weight: 10
      - name: Arbeitspakete
        url: work-packages
        weight: 20
      - name: Team
        url: people
        weight: 30
      - name: Publikationen
        url: publication
        weight: 40
      - name: Neuigkeiten
        url: news
        weight: 50
      - name: Kontakt
        url: contact
        weight: 60
